Repository WSC-Nettie-Owners/wscnettie, pull requests merged in 2023-10, with the labels that each got.

#32 test
  src/routes/about/Thomas
Labels: Documentation, Good First Issue

#35 Ky's first commit
  src/routes/about/Kyla.js
Labels: Documentation, Good First Issue, JavaScript

#37 changing the link colors
  package-lock.json
  src/routes/+page.svelte
Labels: HTML, CSS

#26 Update with Main
  package-lock.json
  package.json
Labels: Good First Issue, Dependencies

#27 Update readme
  README.md
  package.json
Labels: Documentation, Good First Issue

#30 Update README.md
  README.md
Labels: Documentation, Good First Issue
